Go back to base image gcc:8.2.0
Using later versions of boost causes c++ cucumber a problem.
With Boost version: 1.67.0
you get this error...
"/usr/include/boost/regex/v4/match_results.hpp:60:77: error: no type named 'const_reference' in 'class std::allocator<boost::sub_match<const char*> >'\n",